### ISSUE TITLE
Sugestão: Remover lance inicial?

### ISSUE THREAD

**Issue by gagliotti** [GabrielEstevam/gabrielestevam.github.io#2]
Motivos para remover lance inicial: 
- Fica mais simples
- O pessoal pode ser perder com o número de casas após a vírgula 

Qual sua opinião?

**Comment by GabrielEstevam** [comment]
Pode ser, nesse caso precisa estabelecer um valor de lance inicial.
A unidade é gwei, então não precisa ter número com vírgula. O lance mínimo é de 1 gwei, que 1 bilhão de vezes menor que 1 ether.

**Comment by gagliotti** [comment]
Por que precisa de um lance inicial ou inves de deixar livre?

Quanto a gwei, isso pode dar confusão com o saldo no metamask, que está em ether. Não concordas?

**Comment by GabrielEstevam** [comment]
Pode ser sem lance inicial. Só pensei que em um leilão o vendedor não gostaria de entregar o lote abaixo de um determinado valor.

Posso trocar para ether. Vou tentar obter faucet na rinkeby.

**Comment by gagliotti** [comment]
Acho que vale a pena tirar o lance inicial para ficar mais simples.
