### ISSUE TITLE
Trocar campo texto por drop-down list

### ISSUE THREAD

**Issue by gagliotti** [GabrielEstevam/gabrielestevam.github.io#3]
Para o nome do lote, trocar todos os campos de texto por HTML <select> drop-down list.

**Comment by gagliotti** [comment]
O drop-down list deve ser completado com os últimos 15 lotes (eu aumentei, haverá pelo menos 40 inscritos no workshop).

Se funcionar, remover "Últimos lotes:" no final da página

**Comment by GabrielEstevam** [comment]
Coloquei os campos select para selecionar o lote ao dar um lance e solicitar pagamento. Removi o limite de lotes mas ainda não filtrei os lotes ativos ou com pagamentos pendentes.

**Comment by GabrielEstevam** [comment]
Conclui o filtro de lotes e aumentei a precisão do lance para 0.001 ether.
