### ISSUE TITLE
Mudar para leilão de menor preço

### ISSUE THREAD

**Issue by gagliotti** [GabrielEstevam/gabrielestevam.github.io#7]
Comprador cadastra lote e faz um depósito para o lance inicial e define o prazo em blocos.
Vendedores fazem lances menores ou iguais ao deposito
Terminado o prazo, o vendedor de lance minimo recebe o valor do lance. Esse valor é deduzido do deposito.
A diferenca entre o lance mínimo e deposito volta pro comprador.

**Comment by GabrielEstevam** [comment]
Feito. Adicionei a opção de leilão inverso (menor preço). Um check determina se o novo lote será inverso ou não.
